services:
  db:
    image: postgres:latest 

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

    container_name: my-db

    restart: unless-stopped

    ports:
      - "54333:5432"

    env_file: .env

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - backend

  redis:
    image: redis:latest 

    container_name: my-redis

    restart: unless-stopped

    ports:
      - "7963:7963"

    volumes:
      - cachedata:/var/lib/redis/data

    networks:
      - backend

  app:
    image: temptor 

    build: .

    env_file: .env

    ports:
      - "8080:3000"

    depends_on:
      - redis
      - db

    networks:
      - backend

volumes:
  pgdata:
  cachedata:

networks:
  backend:
    driver: bridge
